# Generated by Django 4.2.8 on 2023-12-19 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.basket')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ожидает', 'Ожидает подтверждения'), ('завершен', 'Завершен'), ('отменен', 'Отменен')], default='ожидает', max_length=20)),
                ('is_selected', models.BooleanField(default=False)),
                ('basket_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carts.basketitem')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
